### PR TITLE
Upgrade global-dirs to 1.0.0

### LINKED ISSUE #2: Upgrade global-dirs to 1.0.0
Hi Sindre,

Thanks for all the work you have done! We at Commitlint ❤️ you for it! You recently upgraded `global-dirs` to `1.0.0` to fix some issues we are having too with some homebrew installations. I'll create a PR to include that one here too.

Cheers,
❤️ Cedric

### PR DESCRIPTION
**Pull request by byCedric**
This fixes #2

### CODE REVIEW

**Comment by byCedric** [comment]
Hmm, this is an interesting one! On OSX this works perfectly (even with node installed by Homebrew). But on Linux I can reproduce the issue, it's related to a "wrong" yarn package folder I think. Let me know if I should open an issue on the `global-dirs` repository or if I'm overlooking something.

**OSX**:
```
> npx ava                                                                                          
⠼ { globalDirs:
   { npm:
      { prefix: '/usr/local',
        packages: '/usr/local/lib/node_modules',
        binaries: '/usr/local/bin' },
     yarn:
      { prefix: '/Users/cedric/.config/yarn',
        packages: '/Users/cedric/.config/yarn/global/node_modules',
        binaries: '/Users/cedric/.config/yarn/global/node_modules/.bin' } } }
```

**Linux** (through `docker run -v $PWD:/code -w /code node:10 npx ava`):
```
root@061d5e7d715e:/code# npx ava
⠧ { globalDirs:
   { npm:
      { prefix: '/usr/local',
        packages: '/usr/local/lib/node_modules',
        binaries: '/usr/local/bin' },
     yarn:
      { prefix: '/usr/local',
        packages: '/usr/local/global/node_modules',
        binaries: '/usr/local/global/node_modules/.bin' } } }
```

I don't think the `/usr/local/global` is the proper folder for yarn right? When I manually add something globally through Yarn on the docker/linux instance, I get this path:
```
root@af923ba739ae:/code# yarn global add dog-names
yarn global v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.15.2", while you're on "1.13.0".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
success Installed "dog-names@1.0.2" with binaries:
      - dog-names
Done in 2.47s.
root@af923ba739ae:/code# which dog-names
/usr/local/bin/dog-names
```

**Comment by byCedric** [comment]
The output of `yarn global dir` and `npm root -g` on contained Linux is also quite different:

```
root@af923ba739ae:/code# npm root -g
/usr/local/lib/node_modules
```

```
root@af923ba739ae:/code# yarn global dir
/usr/local/share/.config/yarn/global
```

```
root@af923ba739ae:/code# yarn global bin
/usr/local/bin
```

**Comment by sindresorhus** [comment]
Can you open an issue on `global-dirs`?

**Comment by byCedric** [comment]
Blocked by https://github.com/sindresorhus/global-dirs/issues/13

**Comment by sindresorhus** [comment]
I'm going to close this as it doesn't look like https://github.com/sindresorhus/global-dirs/issues/13 will be resolved anytime soon...

**Pull request closed without merging**
